pool:
  name: PfLocal

variables:
  buildConfiguration: 'Release'

steps:
- checkout: self
- checkout: git://PepDeploy/PepDeploy2
- script: dotnet build PepDeploy/ --configuration $(buildConfiguration) 
  displayName: 'dotnet build $(buildConfiguration)'