pool:
  name: PfLocal

variables:
  buildConfiguration: 'Release'
  azureSubscription: ADO.philipfourie
  appName: pf-pep-hello

steps:
- checkout: self
- script: 
    dotnet build SampleFunc --configuration $(buildConfiguration) --output $(Build.BinariesDirectory)
  displayName: 'dotnet build SampleFunc $(buildConfiguration)'
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)' 
    includeRootFolder: false 
    archiveType: 'zip' # Options: zip, 7z, tar, wim
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip' 
    replaceExistingArchive: true 
- task: AzureFunctionApp@1 # Add this at the end of your file
  inputs:
    azureSubscription: $(azureSubscription)
    appType: functionAppLinux
    appName: $(appName)
    package: $(System.ArtifactsDirectory)/**/*.zip  