pool:
  name: PfLocal

variables:
  buildConfiguration: 'Release'

steps:
- checkout: self
- script: dotnet build SampleFunc/ --configuration $(buildConfiguration) 
  displayName: 'dotnet build SampleFunc $(buildConfiguration)'